In [1]:
%cd VIS_SinhCT_Sinh_f

/Users/trancatkhanh/Desktop/FinanaceFormula/VIS_SinhCT_Sinh_f


In [2]:
import pandas as pd
import numpy as np
import os
data = pd.read_excel("Data_test.xlsx")
data = data[data["TIME"] != 2023]

In [3]:
data = data.drop(columns=['Cash and cash equivalents', 'Total Inventories', 'Fixed assets',
       'Current liabilities', 'Sales', 'Gross profit', 'Net operating profit'])

In [4]:
data.columns

Index(['SYMBOL', 'EXCHANGE', 'TIME', 'PROFIT', 'VALUEARG', 'Profit after tax',
       'Owner's equity'],
      dtype='object')

In [5]:
from generator import Formula_generator
vis = Formula_generator(data,
                        generation_method=2,
                        required_fields=[],
                        multiple_cycles=False,
                        investment_method=0,
                        interest_rate=1.06,
                        measurement_method=2,
                        target=0,
                        diff_p_p_lim = 0.1)

Các cột không được coi là biến: ['TIME', 'PROFIT', 'SYMBOL', 'VALUEARG', 'EXCHANGE']


In [6]:
vis.generate_formula("Data_CT", 100, 5000000000)


Đã tạo thư mục lưu công thức
Data_CT/
Chạy lần đầu . Tiến hành lưu file
Đang chạy sinh công thức, số toán hạng là 2
Đang chạy sinh công thức, số toán hạng là 4
Đang chạy sinh công thức, số toán hạng là 6
Đã lưu lịch sử
Đã lưu công thức
Đang chạy sinh công thức, số toán hạng là 8
Đã lưu lịch sử
Đã lưu công thức
Đang chạy sinh công thức, số toán hạng là 10
Đã lưu lịch sử
Đã lưu công thức
Đang chạy sinh công thức, số toán hạng là 12
Đã lưu lịch sử
Đã sinh xong đến F cuối cùng (12)


In [7]:
vis.generation_method

<bound method Formula_generator.__generation_method_2 of <generator.Formula_generator object at 0x7f82f0aefa60>>

In [8]:
'2' in str(vis.generation_method)[:60]

True

In [9]:
vis.count

array([         0,        100,          0, 5000000000])

In [10]:
l = ['(-0/1) - ((-1/0) * ((-1/0) / (-0/1)))', '(-0/1) - ((-1/0) * ((+1/0) / (+0/1)))', '(-0/1) - ((+1/0) / ((-0/1) * (+0/1)))', '(-0/1) - ((+1/0) / ((+0/1) * (-0/1)))', '(+0/1) - ((-0/1) * ((-1/0) / (-0/1)))', '(+0/1) - ((-0/1) * ((+1/0) / (+0/1)))', '(+0/1) - ((+0/1) / ((-0/1) * (+0/1)))', '(+0/1) - ((+0/1) / ((+0/1) * (-0/1)))', '(+0/1) - ((-1/0) * ((-1/0) / (-0/1)))', '(+0/1) - ((-1/0) * ((+1/0) / (+0/1)))', '(+0/1) - ((+1/0) / ((-0/1) * (+0/1)))', '(+0/1) - ((+1/0) / ((+0/1) * (-0/1)))', '(-1/0) - ((-1/0) * ((-1/0) / (-0/1)))', '(-1/0) - ((-1/0) * ((+1/0) / (+0/1)))', '(-1/0) - ((+1/0) / ((-0/1) * (+0/1)))', '(-1/0) - ((+1/0) / ((+0/1) * (-0/1)))', '(+1/0) - ((-0/1) * ((-1/0) / (-0/1)))', '(+1/0) - ((-0/1) * ((+1/0) / (+0/1)))', '(+1/0) - ((+0/1) / ((-0/1) * (+0/1)))', '(+1/0) - ((+0/1) / ((+0/1) * (-0/1)))', '(+1/0) - ((-1/0) * ((-1/0) / (-0/1)))', '(+1/0) - ((-1/0) * ((+1/0) / (+0/1)))', '(+1/0) - ((+1/0) / ((-0/1) * (+0/1)))', '(+1/0) - ((+1/0) / ((+0/1) * (-0/1)))']



In [11]:
len(l)

24

In [12]:
k = (set(['(-0/1) - ((-1/0) * ((-1/0) / (-0/1)))', '(-0/1) - ((-1/0) * ((+1/0) / (+0/1)))', '(-0/1) - ((+1/0) / ((-0/1) * (+0/1)))', '(-0/1) - ((+1/0) / ((+0/1) * (-0/1)))', '(+0/1) - ((-0/1) * ((-1/0) / (-0/1)))', '(+0/1) - ((-0/1) * ((+1/0) / (+0/1)))', '(+0/1) - ((+0/1) / ((-0/1) * (+0/1)))', '(+0/1) - ((+0/1) / ((+0/1) * (-0/1)))', '(+0/1) - ((-1/0) * ((-1/0) / (-0/1)))', '(+0/1) - ((-1/0) * ((+1/0) / (+0/1)))', '(+0/1) - ((+1/0) / ((-0/1) * (+0/1)))', '(+0/1) - ((+1/0) / ((+0/1) * (-0/1)))', '(-1/0) - ((-1/0) * ((-1/0) / (-0/1)))', '(-1/0) - ((-1/0) * ((+1/0) / (+0/1)))', '(-1/0) - ((+1/0) / ((-0/1) * (+0/1)))', '(-1/0) - ((+1/0) / ((+0/1) * (-0/1)))', '(+1/0) - ((-0/1) * ((-1/0) / (-0/1)))', '(+1/0) - ((-0/1) * ((+1/0) / (+0/1)))', '(+1/0) - ((+0/1) / ((-0/1) * (+0/1)))', '(+1/0) - ((+0/1) / ((+0/1) * (-0/1)))', '(+1/0) - ((-1/0) * ((-1/0) / (-0/1)))', '(+1/0) - ((-1/0) * ((+1/0) / (+0/1)))', '(+1/0) - ((+1/0) / ((-0/1) * (+0/1)))', '(+1/0) - ((+1/0) / ((+0/1) * (-0/1)))']))


In [13]:
kl = 0 
for i in k:
    if i in l:
        kl +=1 
    if i not in l:
        print(i)
print(kl)

24


In [14]:
vis.OPERAND

array([[0.0519885 , 0.00144815, 0.03370255, ..., 0.0179507 , 0.04272564,
        0.03440913],
       [0.87481479, 1.24790156, 0.78220326, ..., 0.32112646, 0.17861851,
        0.25564865]])

In [15]:
-vis.OPERAND[1]

array([-0.87481479, -1.24790156, -0.78220326, ..., -0.32112646,
       -0.17861851, -0.25564865])

In [16]:
expression = '-1/2'

weight = np.zeros(vis.OPERAND.shape[1])
operands = {}
for i, operand in enumerate(vis.OPERAND):
    operands[f'A{i}'] = operand

# Replace numbers with corresponding variable names
for i, operand in enumerate(operands):
    
    expression = expression.replace(str(i), operand)

# Evaluate the expression
result = eval(expression, {}, operands)
weight+=result
print(weight)

[-0.43740739 -0.62395078 -0.39110163 ... -0.16056323 -0.08930926
 -0.12782433]


In [17]:
-vis.OPERAND[1]/vis.OPERAND[2]

IndexError: index 2 is out of bounds for axis 0 with size 2

In [ ]:
expression = '-1/2'

columns = len(vis.OPERAND)
for i in range(columns):
    column_variable = "{}".format(i)
    expression = expression.replace(str(i), column_variable)
print(expression)
for i, column_value in enumerate(vis.OPERAND):
    column_variable = "A{}".format(i)
    expression = expression.replace(column_variable, str(column_value))
    print(column_value)
print(expression)
result = eval(expression)
print(result)

-1/2
[0.31887778 0.39693847 0.1091497  ... 0.06552784 0.03293761 0.07028022]
[0.15996809 0.54479089 0.02084284 ... 0.48107391 0.05940226 0.11634382]
[0.33694847 0.16848317 0.50872368 ... 1.3094114  0.01012113 0.07169651]
[0.5264463  0.03560391 0.13533317 ... 1.61369785 0.19976527 0.24447098]
[2.1097391  0.86121279 0.55345992 ... 2.40196141 0.77384235 0.74539669]
[0.20872438 0.04798185 0.06777231 ... 0.3055042  0.10107666 0.13963524]
[ 0.06497323 -0.00631566  0.03865988 ...  0.01690101  0.03828519
  0.03856156]
[0.0519885  0.00144815 0.03370255 ... 0.0179507  0.04272564 0.03440913]
[0.87481479 1.24790156 0.78220326 ... 0.32112646 0.17861851 0.25564865]
-1/2
-0.5


In [ ]:
vis.count

array([  0, 100, 201, 500])

In [ ]:
import pickle
with open('state.pkl', 'rb') as file:
    state = pickle.load(file)
F_new_formula = state['F_new_formula']
current_formula1 = state['current_formula1']
current_formula2 = state['current_formula2']
current_operator = state['current_operator']
F_thu = state['operand']
F2 = state['F_current']

In [ ]:
F2

['(0/1) + ((0/1) / (3/4))']

In [ ]:
current_formula2

54

In [ ]:
current_operator

0

In [ ]:
current_formula1

0

In [ ]:
%cd /Users/trancatkhanh/Desktop/Data_CT

/Users/trancatkhanh/Desktop/Data_CT


In [ ]:
import pandas as pd
import os
directory = '/Users/trancatkhanh/Desktop/Data_CT/'
merged_data = pd.DataFrame()
for filename in os.listdir(directory):
    if filename.endswith(".csv"):
        file_path = os.path.join(directory, filename)
        df = pd.read_csv(file_path)
        merged_data = pd.concat([merged_data, df])
merged_data = merged_data.drop_duplicates()
merged_data = merged_data.reset_index(drop=True)
merged_data.to_csv('F10.csv', index=False)


In [ ]:
len('(+1/0) - ((-0/1) * ((-1/0) / (-0/1)))')

37

In [ ]:
len(unique_values[1])

48

In [ ]:
df1 = pd.read_csv('/Users/trancatkhanh/Desktop/Data_CT/merged_data.csv')
unique_values = df1['formula'].unique()
l = 0
for i in (unique_values):
    if len(i)==37:
        l +=1
        print(i)
print


(+1/0) - ((-0/1) * ((-1/0) / (-0/1)))
(+1/0) - ((-0/1) * ((+1/0) / (+0/1)))
(+1/0) - ((+0/1) / ((-0/1) * (+0/1)))
(+1/0) - ((+0/1) / ((+0/1) * (-0/1)))
(+1/0) - ((-1/0) * ((-1/0) / (-0/1)))
(+1/0) - ((-1/0) * ((+1/0) / (+0/1)))
(+1/0) - ((+1/0) / ((-0/1) * (+0/1)))
(+1/0) - ((+1/0) / ((+0/1) * (-0/1)))
(-0/1) - ((-1/0) * ((-1/0) / (-0/1)))
(-0/1) - ((-1/0) * ((+1/0) / (+0/1)))
(-0/1) - ((+1/0) / ((-0/1) * (+0/1)))
(-0/1) - ((+1/0) / ((+0/1) * (-0/1)))
(+0/1) - ((-0/1) * ((-1/0) / (-0/1)))
(+0/1) - ((-0/1) * ((+1/0) / (+0/1)))
(+0/1) - ((+0/1) / ((-0/1) * (+0/1)))
(+0/1) - ((+0/1) / ((+0/1) * (-0/1)))
(+0/1) - ((-1/0) * ((-1/0) / (-0/1)))
(+0/1) - ((-1/0) * ((+1/0) / (+0/1)))
(+0/1) - ((+1/0) / ((-0/1) * (+0/1)))
(+0/1) - ((+1/0) / ((+0/1) * (-0/1)))
(-1/0) - ((-1/0) * ((-1/0) / (-0/1)))
(-1/0) - ((-1/0) * ((+1/0) / (+0/1)))
(-1/0) - ((+1/0) / ((-0/1) * (+0/1)))
(-1/0) - ((+1/0) / ((+0/1) * (-0/1)))
24
